export const items=[
    {
      "product_id":1,
      "product_name":"product-name",
      "product_description":"description",
      "product_price":"100",
      "product_image":"cat-1.jpg",
      "product_image_alt":"cat-1",
      "is_available":true
        },
        {
          "product_id":2,
          "product_name":"product-name",
          "product_description":"description",
          "product_price":"100",
          "product_image":"cat-2.jpg",
          "product_image_alt":"cat-2",
          "is_available":true
            },{
              "product_id":3,
              "product_name":"product-name",
              "product_description":"description",
              "product_price":"200",
              "product_image":"cat-3.jpg",
              "product_image_alt":"cat-3",
              "is_available":true
                }
                ,{
                  "product_id":4,
                  "product_name":"product-name",
                  "product_description":"description",
                  "product_price":"200",
                  "product_image":"cat-3.jpg",
                  "product_image_alt":"cat-3",
                  "is_available":true
                    }
                    ,{
                      "product_id":5,
                      "product_name":"product-name",
                      "product_description":"description",
                      "product_price":"200",
                      "product_image":"cat-3.jpg",
                      "product_image_alt":"cat-3",
                      "is_available":true
                        }
  ];